name = "bia-bazi-game-room"
main = "src/room-do.ts"
compatibility_date = "2026-09-26"

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoomDurableObject"

[[migrations]]
tag = "v2"
renamed_classes = [{ from = "GameRoom", to = "GameRoomDurableObject" }]
